---
build_from:
  aarch64: mbentley/ubuntu:18.04-aarch64
  amd64: mbentley/ubuntu:18.04-amd64
  armv7: mbentley/ubuntu:18.04-armv7
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
