---
name: Omada SDN Controller
version: 0.8.0-dev
slug: addon-omada
description: Manage your TP-Link Omada network using a web browser
url: https://github.com/sibest19/hass-addons/tree/main/addon-omada
webui: https://[HOST]:[PORT:8043]
codenotary: codenotary@frenck.dev
startup: services
init: false
arch:
  - aarch64
  - amd64
  - armv7
backup: cold
ports:
  8088/tcp: 8088
  8043/tcp: 8043
  8843/tcp: 8843
  29810/udp: 29810
  29811/tcp: 29811
  29812/tcp: 29812
  29813/tcp: 29813
  29814/tcp: 29814
ports_description:
  8088/tcp: Manage HTTP port
  8043/tcp: Manage HTTPS port
  8843/tcp: "?"
  29810/udp: "?"
  29811/tcp: "?"
  29812/tcp: "?"
  29813/tcp: "?"
  29814/tcp: "?"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  memory_max: int?
  memory_init: int?
image: "ghcr.io/sibest19/{arch}-addon-omada"
